import { POSTURE } from './PostureGraph.js';

/**
 * AnimationCatalog — Asset & procedural motion metadata catalog.
 *
 * Implements Section 6, 7, 14, 24 of the Master Specification:
 * - Semantic animation families (idles, micro-actions, emotions, gestures, locomotion, postures, reactions)
 * - Complete metadata: duration, loop, compatiblePostures, blendDuration, rootMotion, footContact, license
 * - Decouples animation definitions from behavior logic
 */
export const ANIMATION_CATALOG = Object.freeze({
  // ============================================================
  // 1. IDLE & BREATHING BASELINE
  // ============================================================
  idle: {
    id: 'idle',
    family: 'idle',
    category: 'IDLE',
    duration: 0,
    loop: true,
    interruptible: true,
    compatiblePostures: [POSTURE.STANDING, POSTURE.STAND_PREPARE, POSTURE.WALK_STOP, POSTURE.TURNING],
    blendDuration: 0.4,
    rootMotion: 'none',
    footContact: true,
    vrmaPath: null, // Procedural baseline
    license: 'Internal / AO',
    weight: 2.0,
    priority: 1
  },
  'overte_idle': {
    id: 'overte_idle',
    family: 'idle',
    category: 'IDLE',
    duration: 10.0,
    loop: true,
    interruptible: true,
    compatiblePostures: [POSTURE.STANDING],
    blendDuration: 0.5,
    rootMotion: 'none',
    footContact: true,
    vrmaPath: './assets/animations/overte/idle.vrma',
    license: 'Apache-2.0 (Overte)',
    weight: 1.5,
    priority: 1
  },
  'overte_idle_2': {
    id: 'overte_idle_2',
    family: 'idle',
    category: 'IDLE',
    duration: 30.0,
    loop: true,
    interruptible: true,
    compatiblePostures: [POSTURE.STANDING],
    blendDuration: 0.5,
    rootMotion: 'none',
    footContact: true,
    vrmaPath: './assets/animations/overte/idle-2.vrma',
    license: 'Apache-2.0 (Overte)',
    weight: 1.2,
    priority: 1
  },
  'overte_idle_3': {
    id: 'overte_idle_3',
    family: 'idle',
    category: 'IDLE',
    duration: 13.3,
    loop: true,
    interruptible: true,
    compatiblePostures: [POSTURE.STANDING],
    blendDuration: 0.5,
    rootMotion: 'none',
    footContact: true,
    vrmaPath: './assets/animations/overte/idle-3.vrma',
    license: 'Apache-2.0 (Overte)',
    weight: 1.0,
    priority: 1
  },
  'overte_idle_4': {
    id: 'overte_idle_4',
    family: 'idle',
    category: 'IDLE',
    duration: 17.7,
    loop: true,
    interruptible: true,
    compatiblePostures: [POSTURE.STANDING],
    blendDuration: 0.5,
    rootMotion: 'none',
    footContact: true,
    vrmaPath: './assets/animations/overte/idle-4.vrma',
    license: 'Apache-2.0 (Overte)',
    weight: 1.0,
    priority: 1
  },
  'rb_idle': {
    id: 'rb_idle',
    family: 'idle',
    category: 'IDLE',
    duration: 6.0,
    loop: true,
    interruptible: true,
    compatiblePostures: [POSTURE.STANDING],
    blendDuration: 0.5,
    rootMotion: 'none',
    footContact: true,
    vrmaPath: './assets/animations/rocketbox/rb-idle.vrma',
    license: 'MIT (Rocketbox)',
    weight: 1.2,
    priority: 1
  },

  // ============================================================
  // 2. MICRO-ACTIONS & POSTURE ADJUSTMENTS
  // ============================================================
  'overte_relaxed': {
    id: 'overte_relaxed',
    family: 'micro',
    category: 'MICRO',
    duration: 5.5,
    loop: false,
    interruptible: true,
    compatiblePostures: [POSTURE.STANDING],
    blendDuration: 0.4,
    rootMotion: 'none',
    footContact: true,
    vrmaPath: './assets/animations/overte/relaxed.vrma',
    license: 'Apache-2.0 (Overte)',
    weight: 1.0,
    priority: 2
  },
  'overte_relaxed_2': {
    id: 'overte_relaxed_2',
    family: 'micro',
    category: 'MICRO',
    duration: 3.6,
    loop: false,
    interruptible: true,
    compatiblePostures: [POSTURE.STANDING],
    blendDuration: 0.4,
    rootMotion: 'none',
    footContact: true,
    vrmaPath: './assets/animations/overte/relaxed-2.vrma',
    license: 'Apache-2.0 (Overte)',
    weight: 1.0,
    priority: 2
  },
  idle_sway: {
    id: 'idle_sway',
    family: 'micro',
    category: 'MICRO',
    duration: 4.0,
    loop: true,
    interruptible: true,
    compatiblePostures: [POSTURE.STANDING],
    blendDuration: 0.5,
    rootMotion: 'none',
    footContact: true,
    vrmaPath: null,
    license: 'Internal / AO',
    weight: 1.0,
    priority: 1
  },
  stretch: {
    id: 'stretch',
    family: 'stretch',
    category: 'MICRO',
    duration: 3.5,
    loop: false,
    interruptible: true,
    compatiblePostures: [POSTURE.STANDING],
    blendDuration: 0.6,
    rootMotion: 'none',
    footContact: true,
    vrmaPath: null,
    license: 'Internal / AO',
    weight: 1.0,
    priority: 2
  },
  yawn: {
    id: 'yawn',
    family: 'yawn',
    category: 'MICRO',
    duration: 3.0,
    loop: false,
    interruptible: true,
    compatiblePostures: [POSTURE.STANDING, POSTURE.SITTING, POSTURE.SLEEPY],
    blendDuration: 0.5,
    rootMotion: 'none',
    footContact: true,
    vrmaPath: null,
    license: 'Internal / AO',
    weight: 1.0,
    priority: 2
  },

  // ============================================================
  // 3. EMOTIONS & EXPRESSIONS
  // ============================================================
  'overte_neutral': {
    id: 'overte_neutral',
    family: 'neutral',
    category: 'EMOTION',
    duration: 5.0,
    loop: false,
    interruptible: true,
    compatiblePostures: [POSTURE.STANDING],
    blendDuration: 0.4,
    rootMotion: 'none',
    footContact: true,
    vrmaPath: './assets/animations/overte/neutral.vrma',
    license: 'Apache-2.0 (Overte)',
    weight: 1.0,
    priority: 2
  },
  'overte_happy': {
    id: 'overte_happy',
    family: 'happy',
    category: 'EMOTION',
    duration: 5.3,
    loop: false,
    interruptible: true,
    compatiblePostures: [POSTURE.STANDING],
    blendDuration: 0.4,
    rootMotion: 'none',
    footContact: true,
    vrmaPath: './assets/animations/overte/happy.vrma',
    license: 'Apache-2.0 (Overte)',
    weight: 1.5,
    priority: 2
  },
  'rb_happy': {
    id: 'rb_happy',
    family: 'happy',
    category: 'EMOTION',
    duration: 4.2,
    loop: false,
    interruptible: true,
    compatiblePostures: [POSTURE.STANDING],
    blendDuration: 0.4,
    rootMotion: 'none',
    footContact: true,
    vrmaPath: './assets/animations/rocketbox/rb-happy.vrma',
    license: 'MIT (Rocketbox)',
    weight: 1.2,
    priority: 2
  },
  'overte_sad': {
    id: 'overte_sad',
    family: 'sad',
    category: 'EMOTION',
    duration: 3.3,
    loop: false,
    interruptible: true,
    compatiblePostures: [POSTURE.STANDING],
    blendDuration: 0.5,
    rootMotion: 'none',
    footContact: true,
    vrmaPath: './assets/animations/overte/sad.vrma',
    license: 'Apache-2.0 (Overte)',
    weight: 1.0,
    priority: 2
  },
  'rb_sad': {
    id: 'rb_sad',
    family: 'sad',
    category: 'EMOTION',
    duration: 3.8,
    loop: false,
    interruptible: true,
    compatiblePostures: [POSTURE.STANDING],
    blendDuration: 0.5,
    rootMotion: 'none',
    footContact: true,
    vrmaPath: './assets/animations/rocketbox/rb-sad.vrma',
    license: 'MIT (Rocketbox)',
    weight: 1.0,
    priority: 2
  },
  'overte_angry': {
    id: 'overte_angry',
    family: 'angry',
    category: 'EMOTION',
    duration: 2.3,
    loop: false,
    interruptible: true,
    compatiblePostures: [POSTURE.STANDING],
    blendDuration: 0.35,
    rootMotion: 'none',
    footContact: true,
    vrmaPath: './assets/animations/overte/angry.vrma',
    license: 'Apache-2.0 (Overte)',
    weight: 1.0,
    priority: 2
  },
  'rb_angry': {
    id: 'rb_angry',
    family: 'angry',
    category: 'EMOTION',
    duration: 3.0,
    loop: false,
    interruptible: true,
    compatiblePostures: [POSTURE.STANDING],
    blendDuration: 0.35,
    rootMotion: 'none',
    footContact: true,
    vrmaPath: './assets/animations/rocketbox/rb-angry.vrma',
    license: 'MIT (Rocketbox)',
    weight: 1.0,
    priority: 2
  },

  // ============================================================
  // 4. GESTURES & REACTIONS
  // ============================================================
  wave: {
    id: 'wave',
    family: 'wave',
    category: 'GESTURE',
    duration: 2.4,
    loop: false,
    interruptible: true,
    compatiblePostures: [POSTURE.STANDING, POSTURE.SITTING],
    blendDuration: 0.4,
    rootMotion: 'none',
    footContact: true,
    vrmaPath: null,
    license: 'Internal / AO',
    weight: 1.5,
    priority: 2
  },
  'vroid_greet': {
    id: 'vroid_greet',
    family: 'wave',
    category: 'GESTURE',
    duration: 3.0,
    loop: false,
    interruptible: true,
    compatiblePostures: [POSTURE.STANDING],
    blendDuration: 0.4,
    rootMotion: 'none',
    footContact: true,
    vrmaPath: './assets/animations/other/vroid/VRMA_02.vrma',
    license: 'pixiv VRoid Project',
    weight: 1.2,
    priority: 2
  },
  'vroid_peace': {
    id: 'vroid_peace',
    family: 'peace',
    category: 'GESTURE',
    duration: 3.0,
    loop: false,
    interruptible: true,
    compatiblePostures: [POSTURE.STANDING],
    blendDuration: 0.4,
    rootMotion: 'none',
    footContact: true,
    vrmaPath: './assets/animations/other/vroid/VRMA_03.vrma',
    license: 'pixiv VRoid Project',
    weight: 1.0,
    priority: 2
  },
  'vroid_shoot': {
    id: 'vroid_shoot',
    family: 'playful',
    category: 'GESTURE',
    duration: 2.8,
    loop: false,
    interruptible: true,
    compatiblePostures: [POSTURE.STANDING],
    blendDuration: 0.35,
    rootMotion: 'none',
    footContact: true,
    vrmaPath: './assets/animations/other/vroid/VRMA_04.vrma',
    license: 'pixiv VRoid Project',
    weight: 1.0,
    priority: 2
  },
  'vroid_spin': {
    id: 'vroid_spin',
    family: 'spin',
    category: 'GESTURE',
    duration: 3.2,
    loop: false,
    interruptible: true,
    compatiblePostures: [POSTURE.STANDING],
    blendDuration: 0.4,
    rootMotion: 'none',
    footContact: true,
    vrmaPath: './assets/animations/other/vroid/VRMA_05.vrma',
    license: 'pixiv VRoid Project',
    weight: 0.8,
    priority: 2
  },
  'vroid_model_pose': {
    id: 'vroid_model_pose',
    family: 'pose',
    category: 'GESTURE',
    duration: 3.5,
    loop: false,
    interruptible: true,
    compatiblePostures: [POSTURE.STANDING],
    blendDuration: 0.4,
    rootMotion: 'none',
    footContact: true,
    vrmaPath: './assets/animations/other/vroid/VRMA_06.vrma',
    license: 'pixiv VRoid Project',
    weight: 0.8,
    priority: 2
  },
  'overte_nod': {
    id: 'overte_nod',
    family: 'nod',
    category: 'GESTURE',
    duration: 1.8,
    loop: false,
    interruptible: true,
    compatiblePostures: [POSTURE.STANDING, POSTURE.SITTING],
    blendDuration: 0.3,
    rootMotion: 'none',
    footContact: true,
    vrmaPath: './assets/animations/overte/nod.vrma',
    license: 'Apache-2.0 (Overte)',
    weight: 1.5,
    priority: 2
  },
  'overte_shake': {
    id: 'overte_shake',
    family: 'shake',
    category: 'GESTURE',
    duration: 2.3,
    loop: false,
    interruptible: true,
    compatiblePostures: [POSTURE.STANDING, POSTURE.SITTING],
    blendDuration: 0.3,
    rootMotion: 'none',
    footContact: true,
    vrmaPath: './assets/animations/overte/shake.vrma',
    license: 'Apache-2.0 (Overte)',
    weight: 1.2,
    priority: 2
  },
  'overte_think': {
    id: 'overte_think',
    family: 'think',
    category: 'GESTURE',
    duration: 3.4,
    loop: false,
    interruptible: true,
    compatiblePostures: [POSTURE.STANDING, POSTURE.SITTING],
    blendDuration: 0.4,
    rootMotion: 'none',
    footContact: true,
    vrmaPath: './assets/animations/overte/think.vrma',
    license: 'Apache-2.0 (Overte)',
    weight: 1.2,
    priority: 2
  },
  'overte_raise_hand': {
    id: 'overte_raise_hand',
    family: 'raise_hand',
    category: 'GESTURE',
    duration: 10.0,
    loop: false,
    interruptible: true,
    compatiblePostures: [POSTURE.STANDING],
    blendDuration: 0.4,
    rootMotion: 'none',
    footContact: true,
    vrmaPath: './assets/animations/overte/raise-hand.vrma',
    license: 'Apache-2.0 (Overte)',
    weight: 1.0,
    priority: 2
  },
  'rb_listen': {
    id: 'rb_listen',
    family: 'listen',
    category: 'REACTION',
    duration: 4.5,
    loop: true,
    interruptible: true,
    compatiblePostures: [POSTURE.STANDING, POSTURE.SITTING],
    blendDuration: 0.4,
    rootMotion: 'none',
    footContact: true,
    vrmaPath: './assets/animations/rocketbox/rb-listen.vrma',
    license: 'MIT (Rocketbox)',
    weight: 1.0,
    priority: 2
  },
  think: {
    id: 'think',
    family: 'think',
    category: 'GESTURE',
    duration: 4.0,
    loop: false,
    interruptible: true,
    compatiblePostures: [POSTURE.STANDING, POSTURE.SITTING],
    blendDuration: 0.5,
    rootMotion: 'none',
    footContact: true,
    vrmaPath: null,
    license: 'Internal / AO',
    weight: 1.0,
    priority: 2
  },
  confused: {
    id: 'confused',
    family: 'confused',
    category: 'GESTURE',
    duration: 2.5,
    loop: false,
    interruptible: true,
    compatiblePostures: [POSTURE.STANDING, POSTURE.SITTING],
    blendDuration: 0.3,
    rootMotion: 'none',
    footContact: true,
    vrmaPath: null,
    license: 'Internal / AO',
    weight: 1.0,
    priority: 2
  },
  shy: {
    id: 'shy',
    family: 'shy',
    category: 'GESTURE',
    duration: 3.2,
    loop: false,
    interruptible: true,
    compatiblePostures: [POSTURE.STANDING, POSTURE.SITTING],
    blendDuration: 0.4,
    rootMotion: 'none',
    footContact: true,
    vrmaPath: null,
    license: 'Internal / AO',
    weight: 1.0,
    priority: 2
  },
  pet: {
    id: 'pet',
    family: 'pet',
    category: 'GESTURE',
    duration: 2.8,
    loop: false,
    interruptible: true,
    compatiblePostures: [POSTURE.STANDING, POSTURE.SITTING],
    blendDuration: 0.3,
    rootMotion: 'none',
    footContact: true,
    vrmaPath: null,
    license: 'Internal / AO',
    weight: 1.0,
    priority: 3
  },

  // ============================================================
  // 5. LOCOMOTION
  // ============================================================
  walk: {
    id: 'walk',
    family: 'walk',
    category: 'LOCOMOTION',
    duration: 0,
    loop: true,
    interruptible: true,
    compatiblePostures: [POSTURE.WALKING, POSTURE.WALK_START, POSTURE.STANDING],
    blendDuration: 0.35,
    rootMotion: 'none',
    footContact: true,
    vrmaPath: null,
    license: 'Internal / AO',
    weight: 2.0,
    priority: 2
  },
  'overte_walk': {
    id: 'overte_walk',
    family: 'walk',
    category: 'LOCOMOTION',
    duration: 1.0,
    loop: true,
    interruptible: true,
    compatiblePostures: [POSTURE.WALKING, POSTURE.WALK_START, POSTURE.STANDING],
    blendDuration: 0.3,
    rootMotion: 'none',
    footContact: true,
    vrmaPath: './assets/animations/overte/world-walk.vrma',
    license: 'Apache-2.0 (Overte)',
    weight: 1.5,
    priority: 2
  },
  'overte_walk_slow': {
    id: 'overte_walk_slow',
    family: 'walk',
    category: 'LOCOMOTION',
    duration: 1.3,
    loop: true,
    interruptible: true,
    compatiblePostures: [POSTURE.WALKING, POSTURE.WALK_START, POSTURE.STANDING],
    blendDuration: 0.35,
    rootMotion: 'none',
    footContact: true,
    vrmaPath: './assets/animations/overte/world-walk-slow.vrma',
    license: 'Apache-2.0 (Overte)',
    weight: 1.0,
    priority: 2
  },
  'overte_walk_start': {
    id: 'overte_walk_start',
    family: 'walk_start',
    category: 'LOCOMOTION',
    duration: 0.4,
    loop: false,
    interruptible: false,
    compatiblePostures: [POSTURE.WALK_START],
    blendDuration: 0.2,
    rootMotion: 'none',
    footContact: true,
    vrmaPath: './assets/animations/overte/world-walk-start.vrma',
    license: 'Apache-2.0 (Overte)',
    weight: 1.0,
    priority: 2
  },
  'overte_walk_stop': {
    id: 'overte_walk_stop',
    family: 'walk_stop',
    category: 'LOCOMOTION',
    duration: 1.9,
    loop: false,
    interruptible: false,
    compatiblePostures: [POSTURE.WALK_STOP],
    blendDuration: 0.3,
    rootMotion: 'none',
    footContact: true,
    vrmaPath: './assets/animations/overte/world-walk-stop.vrma',
    license: 'Apache-2.0 (Overte)',
    weight: 1.0,
    priority: 2
  },
  run: {
    id: 'run',
    family: 'run',
    category: 'LOCOMOTION',
    duration: 0,
    loop: true,
    interruptible: true,
    compatiblePostures: [POSTURE.WALKING],
    blendDuration: 0.3,
    rootMotion: 'none',
    footContact: true,
    vrmaPath: null,
    license: 'Internal / AO',
    weight: 1.0,
    priority: 2
  },

  // ============================================================
  // 6. POSTURES (SEATED, RESTING, SQUATTING)
  // ============================================================
  sit_prepare: {
    id: 'sit_prepare',
    family: 'sit_prepare',
    category: 'POSTURE',
    duration: 1.2,
    loop: false,
    interruptible: false,
    compatiblePostures: [POSTURE.SIT_PREPARE, POSTURE.STANDING],
    blendDuration: 0.8,
    rootMotion: 'none',
    footContact: true,
    vrmaPath: null,
    license: 'Internal / AO',
    weight: 1.0,
    priority: 3
  },
  'quaternius_sit_enter': {
    id: 'quaternius_sit_enter',
    family: 'sit_prepare',
    category: 'POSTURE',
    duration: 1.4,
    loop: false,
    interruptible: false,
    compatiblePostures: [POSTURE.SIT_PREPARE, POSTURE.STANDING],
    blendDuration: 0.5,
    rootMotion: 'none',
    footContact: true,
    vrmaPath: './assets/animations/quaternius/world-sit-enter.vrma',
    license: 'CC0 (Quaternius)',
    weight: 1.5,
    priority: 3
  },
  sit: {
    id: 'sit',
    family: 'sit',
    category: 'POSTURE',
    duration: 0,
    loop: true,
    interruptible: true,
    compatiblePostures: [POSTURE.SITTING, POSTURE.RESTING],
    blendDuration: 0.8,
    rootMotion: 'none',
    footContact: true,
    vrmaPath: null,
    license: 'Internal / AO',
    weight: 1.0,
    priority: 2
  },
  'overte_sit_idle': {
    id: 'overte_sit_idle',
    family: 'sit',
    category: 'POSTURE',
    duration: 13.3,
    loop: true,
    interruptible: true,
    compatiblePostures: [POSTURE.SITTING, POSTURE.RESTING],
    blendDuration: 0.6,
    rootMotion: 'none',
    footContact: true,
    vrmaPath: './assets/animations/overte/world-sit-idle.vrma',
    license: 'Apache-2.0 (Overte)',
    weight: 1.5,
    priority: 2
  },
  'overte_sit_talking': {
    id: 'overte_sit_talking',
    family: 'sit_talking',
    category: 'POSTURE',
    duration: 7.1,
    loop: true,
    interruptible: true,
    compatiblePostures: [POSTURE.SITTING],
    blendDuration: 0.5,
    rootMotion: 'none',
    footContact: true,
    vrmaPath: './assets/animations/overte/world-sit-talking.vrma',
    license: 'Apache-2.0 (Overte)',
    weight: 1.2,
    priority: 2
  },
  stand_prepare: {
    id: 'stand_prepare',
    family: 'stand_prepare',
    category: 'POSTURE',
    duration: 1.0,
    loop: false,
    interruptible: false,
    compatiblePostures: [POSTURE.STAND_PREPARE, POSTURE.SITTING],
    blendDuration: 0.7,
    rootMotion: 'none',
    footContact: true,
    vrmaPath: null,
    license: 'Internal / AO',
    weight: 1.0,
    priority: 3
  },
  'quaternius_sit_exit': {
    id: 'quaternius_sit_exit',
    family: 'stand_prepare',
    category: 'POSTURE',
    duration: 1.5,
    loop: false,
    interruptible: false,
    compatiblePostures: [POSTURE.STAND_PREPARE, POSTURE.SITTING],
    blendDuration: 0.5,
    rootMotion: 'none',
    footContact: true,
    vrmaPath: './assets/animations/quaternius/world-sit-exit.vrma',
    license: 'CC0 (Quaternius)',
    weight: 1.5,
    priority: 3
  },
  sleep: {
    id: 'sleep',
    family: 'sleep',
    category: 'POSTURE',
    duration: 0,
    loop: true,
    interruptible: true,
    compatiblePostures: [POSTURE.SLEEPING, POSTURE.RESTING],
    blendDuration: 1.0,
    rootMotion: 'none',
    footContact: true,
    vrmaPath: null,
    license: 'Internal / AO',
    weight: 1.0,
    priority: 2
  },
  'vroid_squat': {
    id: 'vroid_squat',
    family: 'squat',
    category: 'POSTURE',
    duration: 3.5,
    loop: false,
    interruptible: true,
    compatiblePostures: [POSTURE.STANDING, POSTURE.SQUATTING],
    blendDuration: 0.5,
    rootMotion: 'none',
    footContact: true,
    vrmaPath: './assets/animations/other/vroid/VRMA_07.vrma',
    license: 'pixiv VRoid Project',
    weight: 1.0,
    priority: 2
  }
});

/**
 * Retrieves metadata for a specific animation ID with fallback to idle.
 */
export function getAnimationMetadata(id) {
  return ANIMATION_CATALOG[id] || ANIMATION_CATALOG.idle;
}

/**
 * Retrieves all animations belonging to a semantic family compatible with given posture.
 */
export function getAnimationsByFamily(family, posture = POSTURE.STANDING) {
  return Object.values(ANIMATION_CATALOG).filter(anim => 
    anim.family === family && anim.compatiblePostures.includes(posture)
  );
}

/**
 * Retrieves all animations in a category.
 */
export function getAnimationsByCategory(category) {
  return Object.values(ANIMATION_CATALOG).filter(anim => anim.category === category);
}
